version: "3.7"

services:

  vue-code-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: vue-code-server
    container_name: vue-code-server
    environment:
      TZ: "America/Chicago"
    ports:
      - "3000:3000"
      - "8080:8080"
      - "8081:8081"
    command: coder_server --port 8081 --auth none
    working_dir: /opt/html/
    volumes:
      - $PWD/root:/root
      - $PWD/html:/opt/html

      
