version: "3.7"

services:

  vuetify-code-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: vuetify-code-server
    container_name: vuetify-code-server
    environment:
      TZ: "America/Chicago"
    ports:
      - "8080:8080"
      - "8081:8081"
    working_dir: /opt/html/vuetify
    volumes:
      - $PWD/root:/root
      - $PWD/html:/opt/html

      
